package no.uib.inf252.katscan.view.project;

import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import no.uib.inf252.katscan.project.KatNode;
import no.uib.inf252.katscan.project.ProjectHandler;

/**
 *
 * @author Marcelo Lima
 */
public class ProjectBrowser extends javax.swing.JPanel {

    /**
     * Creates new form DatasetBrowser
     */
    public ProjectBrowser() {
        initComponents();
        
        ProjectBrowserRenderer renderer = new ProjectBrowserRenderer();
        treDatasets.setCellRenderer(renderer);
        treDatasets.setShowsRootHandles(false);
        treDatasets.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        treDatasets.setModel(ProjectHandler.getInstance());
        treDatasets.setSelectionRow(0);
        treDatasets.setDraggable(true);
        treDatasets.setDragHandler(new ProjectDraggableHandler());

        treDatasets.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    showPopup(e.getX(), e.getY());
                }
            }
        });

        treDatasets.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (e.getKeyChar() == ' ') {
                    TreePath node = treDatasets.getSelectionPath();
                    if (node == null) {
                        return;
                    }
                    
                    Rectangle pathBounds = treDatasets.getPathBounds(node);
                    showPopup(pathBounds.x + pathBounds.width / 2, pathBounds.y + pathBounds.height / 2);
                }
            }
        });
        
    }
    
    public void focusTree() {
        treDatasets.requestFocusInWindow();
    }
    
    private void showPopup(int x, int y) {
        TreePath path = treDatasets.getPathForLocation(x, y);
        if (path == null) {
            return;
        }

        KatNode node = (KatNode) path.getLastPathComponent();
        JPopupMenu popupMenu = node.getPopupMenu();
        if (popupMenu != null) {
            popupMenu.show(treDatasets, x, y);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        scrDatasets = new javax.swing.JScrollPane();
        treDatasets = new no.uib.inf252.katscan.view.component.draggable.DraggableTree();

        setLayout(new java.awt.BorderLayout());

        treDatasets.setModel(null);
        scrDatasets.setViewportView(treDatasets);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrDatasets, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrDatasets, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane scrDatasets;
    private no.uib.inf252.katscan.view.component.draggable.DraggableTree treDatasets;
    // End of variables declaration//GEN-END:variables

}
