package no.uib.inf252.katscan.view.project;

import java.awt.Component;
import javax.swing.JTree;
import javax.swing.tree.TreeCellRenderer;
import no.uib.inf252.katscan.project.KatNode;

/**
 *
 * @author Marcelo Lima
 */
public class ProjectBrowserRenderer extends javax.swing.JPanel implements TreeCellRenderer {

    /** Creates new form DatasetBrowserItem */
    public ProjectBrowserRenderer() {
        initComponents();
    }

    @Override
    public Component getTreeCellRendererComponent(JTree tree, Object value,
            boolean selected, boolean expanded, boolean leaf, int row,
            boolean hasFocus) {
        lbltem.setText(value.toString());
        lbltem.setIcon(((KatNode)value).getIcon());
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltem = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbltem.setText("jLabel1");
        add(lbltem, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbltem;
    // End of variables declaration//GEN-END:variables

}
