package no.uib.inf252.katscan.view;

import com.mflima.flowingframes.FlowingLayout;
import com.mflima.flowingframes.FlowingView;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import no.uib.inf252.katscan.data.LoadedDataHolder;
import no.uib.inf252.katscan.data.VoxelMatrix;
import no.uib.inf252.katscan.io.DatLoadSaveHandler;
import no.uib.inf252.katscan.view.component.SwingSliceNavigator;
import no.uib.inf252.katscan.view.opengl.SliceNavigator;
import no.uib.inf252.katscan.view.opengl.CubeRenderer;
import no.uib.inf252.katscan.view.opengl.CubeRenderer;
import no.uib.inf252.katscan.view.opengl.VolumeRenderer;

/**
 *
 * @author Marcelo Lima
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String ICON_NAME = "/icons/iconSmall.png";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            setIconImage(ImageIO.read(getClass().getResource(ICON_NAME)));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        setTitle("KATscans");
//        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

        initComponents();
        setBounds(0, 0, 1000, 1000);

//        JComponent nav = new SliceNavigator();
//        nav.setPreferredSize(new Dimension(500, 500));
//        pnlBack.add(new FlowingView(nav), FlowingLayout.POSITION_ONE);
        
//        JComponent tester = new VerySimpleShader();
//        JComponent tester = new SliceNavigator();
//        JComponent tester = new CubeRenderer();
        JComponent tester = new VolumeRenderer();
        pnlBack.setLayout(new BorderLayout());
        pnlBack.add(new FlowingView(tester));
        revalidate();
        
        tester.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new no.uib.inf252.katscan.view.component.BackgroundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        com.mflima.flowingframes.FlowingLayout flowingLayout1 = new com.mflima.flowingframes.FlowingLayout();
        flowingLayout1.setVerticalLayout(true);
        pnlBack.setLayout(flowingLayout1);
        getContentPane().add(pnlBack, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private no.uib.inf252.katscan.view.component.BackgroundPanel pnlBack;
    // End of variables declaration//GEN-END:variables

}
