package no.uib.inf252.katscan.view;

import com.mflima.flowingframes.FlowingLayout;
import com.mflima.flowingframes.FlowingView;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import no.uib.inf252.katscan.data.VoxelMatrix;
import no.uib.inf252.katscan.io.DatLoadSaveHandler;
import no.uib.inf252.katscan.view.component.SwingSliceNavigator;
import no.uib.inf252.katscan.view.opengl.SliceNavigator;

/**
 *
 * @author Marcelo Lima
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String ICON_NAME = "/icons/iconSmall.png";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            setIconImage(ImageIO.read(getClass().getResource(ICON_NAME)));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        setTitle("KATscans");
//        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

        initComponents();

        InputStream stream;
        try {
            stream = new FileInputStream(new File("misc/sinusveins-256x256x166.dat"));
            DatLoadSaveHandler loadSave = new DatLoadSaveHandler();
            VoxelMatrix loadedData = loadSave.loadData(stream);

            SwingSliceNavigator nav = new SwingSliceNavigator();
            nav.setMatrix(loadedData);
            nav.setPreferredSize(new Dimension(256, 256));
            pnlBack.add(new FlowingView(nav), FlowingLayout.POSITION_ONE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        VerySimpleShader tester = new VerySimpleShader();
        SliceNavigator tester = new SliceNavigator();
        pnlBack.add(new FlowingView(tester), FlowingLayout.POSITION_TWO);
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new no.uib.inf252.katscan.view.component.BackgroundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        com.mflima.flowingframes.FlowingLayout flowingLayout1 = new com.mflima.flowingframes.FlowingLayout();
        flowingLayout1.setVerticalLayout(true);
        pnlBack.setLayout(flowingLayout1);
        getContentPane().add(pnlBack, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private no.uib.inf252.katscan.view.component.BackgroundPanel pnlBack;
    // End of variables declaration//GEN-END:variables

}
