/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mflima.katscans.view;

import java.awt.GraphicsConfiguration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/** @author mflim_000 */
public class SplashScreen extends javax.swing.JDialog {

  /** Creates new form SplashScreen */
  public SplashScreen(JFrame owner, GraphicsConfiguration gc) {
    super(owner, "KATscans", true, gc);

    setResizable(false);
    setUndecorated(true);

    initComponents();

    setSize(pnlBackground.getWidth(), pnlBackground.getHeight());
    setLocationRelativeTo(null);

    new Thread(() -> {
      double value = 0d;
      while (value <= 1d) {
        value += (Math.random() / 8d);
        pgrProgress.setValue(value);

        try {
          Thread.sleep(100);
        } catch (InterruptedException ex) {
          Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

      float mix = 0f;
      while (mix < 1f) {
        mix += 0.1f;
        pnlBackground.setMix(mix);

        try {
          Thread.sleep(50);
        } catch (InterruptedException ex) {
          Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

      try {
        Thread.sleep(500);
      } catch (InterruptedException ex) {
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
      }

      SplashScreen.this.setVisible(false);
      SplashScreen.this.dispose();
    }).start();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlBackground = new com.mflima.katscans.view.component.image.SplashImage();
    pnlTitle = new javax.swing.JPanel();
    btnClose = new javax.swing.JButton();
    pgrProgress = new com.mflima.katscans.view.component.ProgressBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

    pnlBackground.setLayout(new java.awt.BorderLayout());

    pnlTitle.setOpaque(false);
    pnlTitle.setLayout(new java.awt.BorderLayout());

    btnClose.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/icons/exit_bw.png"))); // NOI18N
    btnClose.setBorder(null);
    btnClose.setBorderPainted(false);
    btnClose.setContentAreaFilled(false);
    btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnClose.setMaximumSize(new java.awt.Dimension(26, 26));
    btnClose.setMinimumSize(new java.awt.Dimension(26, 26));
    btnClose.setPreferredSize(new java.awt.Dimension(26, 26));
    btnClose.setRolloverIcon(
        new javax.swing.ImageIcon(getClass().getResource("/icons/exit_over.png"))); // NOI18N
    btnClose.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
          }
        });
    pnlTitle.add(btnClose, java.awt.BorderLayout.EAST);

    pnlBackground.add(pnlTitle, java.awt.BorderLayout.PAGE_START);

    pgrProgress.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pgrProgress.setForeground(new java.awt.Color(180, 180, 180));
    pgrProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    pgrProgress.setGapThickness(2);
    pgrProgress.setPreferredSize(new java.awt.Dimension(32, 26));
    pgrProgress.setProgressBorderColor(new java.awt.Color(85, 127, 85));
    pgrProgress.setProgressColor(new java.awt.Color(85, 127, 85));
    pgrProgress.setValue(0.7);
    pnlBackground.add(pgrProgress, java.awt.BorderLayout.SOUTH);

    getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnCloseActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnCloseActionPerformed
    System.exit(0);
  } // GEN-LAST:event_btnCloseActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private com.mflima.katscans.view.component.ProgressBar pgrProgress;
  private com.mflima.katscans.view.component.image.SplashImage pnlBackground;
  private javax.swing.JPanel pnlTitle;
  // End of variables declaration//GEN-END:variables
}
